### ISSUE TITLE
lighters dont change their textures upon renaming them to a skins name in the anvil

### ISSUE THREAD

**Issue by mircowuffwuff** [mircowuffwuff/create-diesel-generators-fabric-restitched#7]
to reproduce:

1. grab lighter
2. rename it to "creeper" in the anvil
3. witness its skin staying the default one:
![image](https://github.com/user-attachments/assets/219c2a77-10bd-4d52-89a0-056d44c5884c)

when it should have changed to the creeper skin:
![image](https://github.com/user-attachments/assets/dc9543ca-a763-46b9-b2fa-de6695653131)

**Comment by mircowuffwuff** [comment]
problem prolly lies somewhere in LighterItemRenderer.java

**Comment by mircowuffwuff** [comment]
> problem prolly lies somewhere in LighterItemRenderer.java

this class is actually not used at all, its singular usage is commented out in [CreateDieselGeneratorsClient.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/CreateDieselGeneratorsClient.java)

taking a look at [blaji of undying](https://github.com/enjarai/blahaj-of-undying) for reference might be worth a shot

**Comment by mircowuffwuff** [comment]
i didn't expect this to work, but just for protocol: uncommenting line 55 in [CreateDieselGeneratorsClient.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/CreateDieselGeneratorsClient.java)

```java
        //BuiltinItemRendererRegistry.INSTANCE.register(ItemRegistry.LIGHTER, new LighterItemRenderer());
```
to
```java
        BuiltinItemRendererRegistry.INSTANCE.register(ItemRegistry.LIGHTER, new LighterItemRenderer());
```
does not seem to make any difference

**Comment by mircowuffwuff** [comment]
just noticed
```java
    public static final ItemEntry<LighterItem> LIGHTER = REGISTRATE.item("lighter", LighterItem::new)
          //  .transform((CreateRegistrate.customRenderedItem(() -> LighterItemRenderer::new)))
            .register();
```
in [ItemRegistry.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/items/ItemRegistry.java).

i have not yet tried uncommenting line 20 in [ItemRegistry.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/items/ItemRegistry.java)
```java
          //  .transform((CreateRegistrate.customRenderedItem(() -> LighterItemRenderer::new)))
```
to
```java
            .transform((CreateRegistrate.customRenderedItem(() -> LighterItemRenderer::new)))
```
in combination with uncommenting line 55 in [CreateDieselGeneratorsClient.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/CreateDieselGeneratorsClient.java)
```java
        //BuiltinItemRendererRegistry.INSTANCE.register(ItemRegistry.LIGHTER, new LighterItemRenderer());
```
to
```java
        BuiltinItemRendererRegistry.INSTANCE.register(ItemRegistry.LIGHTER, new LighterItemRenderer());
```
but theres probably a reason why mrsterner originally commented these lines out, riiight?

**Comment by mircowuffwuff** [comment]
results in
```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'createdieselgenerators' at 'com.jesz.createdieselgenerators.CreateDieselGeneratorsClient'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:458)
	at knot//net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.IllegalArgumentException: Item createdieselgenerators:lighter already has a builtin renderer!
	at knot//net.fabricmc.fabric.impl.client.rendering.BuiltinItemRendererRegistryImpl.register(BuiltinItemRendererRegistryImpl.java:57)
	at knot//com.jesz.createdieselgenerators.CreateDieselGeneratorsClient.onInitializeClient(CreateDieselGeneratorsClient.java:55)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more
```

**Comment by mircowuffwuff** [comment]
note onModelRegistry in [CreateDieselGeneratorsClient.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/CreateDieselGeneratorsClient.java)

**Comment by mircowuffwuff** [comment]
for protocol: uncommenting line 20 in [ItemRegistry.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/items/ItemRegistry.java)
```java
          //  .transform((CreateRegistrate.customRenderedItem(() -> LighterItemRenderer::new)))
```
to
```java
            .transform((CreateRegistrate.customRenderedItem(() -> LighterItemRenderer::new)))
```
results in very glitched behaviour, like other models missing and menus being invisible upon entering a world. the lighter is glitched as well

**Comment by mircowuffwuff** [comment]
the problem has become appearant: when doing
```java
renderer.render(PartialModels.lighterSkinModels.get(CreateDieselGeneratorsClient.lighterSkins.get(stack.getHoverName().getString().toLowerCase())).getSecond().getFirst().get(), light);
```
then the get() method is from within [CDGPartialModel.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/other/CDGPartialModel.java)
this get() is supposed to return the CDGPartialModel's bakedModel, which is set at no point in code, since the onModelRegistry and onModelBake methods are commented out.
```java
    /*
    public static void onModelRegistry(ModelEvent.RegisterAdditional event) {
        for (CDGPartialModel partial : ALL)
            event.register(partial.getLocation());
    }

    public static void onModelBake(ModelEvent.BakingCompleted event) {
        Map<ResourceLocation, BakedModel> models = event.getModels();
        for (CDGPartialModel partial : ALL)
            partial.set(models.get(partial.getLocation()));
    }

     */
```
uncommenting them results in the class ModelEvent not being found

one should tackle this by finding where the onModelRegistry and or onModelBake would have been called from in the original forge version of the mod, since they are public static methods and what their usages were replaced by in mrsterner's fabric port

perhaps that same replacement could be suited to get the model for calling renderer.render() in [LighterItemRenderer.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/items/LighterItemRenderer.java)

**Comment by mircowuffwuff** [comment]
alternatively one could rewrite that whole loading of the json models as CDGPartialModels to loading them as a renderer.render() compatible model, a BakedModel directly

that actually brings up the question what a BakedModel even is and how one obtains one from a json model file

**Comment by mircowuffwuff** [comment]
changing
```java
    public static Map<String, Pair<CDGPartialModel, Pair<CDGPartialModel, CDGPartialModel>>> lighterSkinModels = new HashMap<>();
    public static void init(){}
    public static void initSkins(){
        lighterSkinModels.clear();
        lighterSkinModels.put("standard", Pair.of(new CDGPartialModel(new ResourceLocation("createdieselgenerators:item/lighter"))
                , Pair.of(new CDGPartialModel(new ResourceLocation("createdieselgenerators:item/lighter_open"))
                        , new CDGPartialModel(new ResourceLocation("createdieselgenerators:item/lighter_ignited")))));
        CreateDieselGeneratorsClient.lighterSkins.forEach((name, skinId) -> {
            lighterSkinModels.put(skinId, Pair.of(new CDGPartialModel(new ResourceLocation("createdieselgenerators:item/lighter/"+skinId))
                    , Pair.of(new CDGPartialModel(new ResourceLocation("createdieselgenerators:item/lighter/"+skinId+"_open"))
                    , new CDGPartialModel(new ResourceLocation("createdieselgenerators:item/lighter/"+skinId+"_ignited")))));
        });
    }
```
to
```java
    public static void initSkins(){
        lighterSkinModels.clear();
        lighterSkinModels.put("standard", Pair.of(new PartialModel(new ResourceLocation("createdieselgenerators:item/lighter"))
                , Pair.of(new PartialModel(new ResourceLocation("createdieselgenerators:item/lighter_open"))
                        , new PartialModel(new ResourceLocation("createdieselgenerators:item/lighter_ignited")))));
        CreateDieselGeneratorsClient.lighterSkins.forEach((name, skinId) -> {
            lighterSkinModels.put(skinId, Pair.of(new PartialModel(new ResourceLocation("createdieselgenerators:item/lighter/"+skinId))
                    , Pair.of(new PartialModel(new ResourceLocation("createdieselgenerators:item/lighter/"+skinId+"_open"))
                    , new PartialModel(new ResourceLocation("createdieselgenerators:item/lighter/"+skinId+"_ignited")))));
        });
    }
```
in [PartialModels.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/PartialModels.java) and uncommenting
```java
          //  .transform((CreateRegistrate.customRenderedItem(() -> LighterItemRenderer::new)))
```
to
```java
            .transform((CreateRegistrate.customRenderedItem(() -> LighterItemRenderer::new)))
```
in [ItemRegistry.java](https://github.com/mircey/create-diesel-generators-fabric-restitched/blob/1.20.1/src/main/java/com/jesz/createdieselgenerators/items/ItemRegistry.java) solves #6 but still no lighter skins

**Comment by mircowuffwuff** [comment]
fixed in https://github.com/mircey/create-diesel-generators-fabric-restitched/commit/4d7582b8e973aac87da95ef3c6c407bd8d2c3f39, will be included in rel3+ versions of the mod
